/**************************************************************************************
                                                                                       
                      LA CLASSE SUIVANTE CORRESPOND AUX INTERFACES                     
                                  DE L'ANESTHESISTE                                    
                          PAS ENCORE FINI MAIS ALORS PAS DU TOUT                       
 *************************************************************************************/

package Interface;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
 
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author camille
 */
public class ANESTHESISTE_Accueil extends javax.swing.JFrame {
    String nom_fichier_image = "Background02.png";
     
    
/****************************************************************
                            CONSTRUCTEUR                         
****************************************************************/ 
    public ANESTHESISTE_Accueil() {
        
        super("Connexion");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setExtendedState(ANESTHESISTE_Accueil.MAXIMIZED_BOTH); 
        initComponents();
        Dimension sizeBckgrd = this.getSize();
        Label_bckgrd.setSize(sizeBckgrd);       
        pack();
        this.setVisible(true);
        URL resource = SA_Accueil.class.getResource("/Images/AccueilOn.png");
        Icon warnIcon = new ImageIcon(resource);
        Button_Accueil.setIcon(warnIcon);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Deconexion = new javax.swing.JButton();
        Button_Accueil = new javax.swing.JButton();
        Panel_Accueil = new javax.swing.JPanel();
        Btn_InformationPatient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_ListPatient = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Text_RshPrenomPatient = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Text_RshNomPatient = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Label_bckgrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        Button_Deconexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Deconnexion.png"))); // NOI18N
        Button_Deconexion.setMaximumSize(new java.awt.Dimension(213, 213));
        Button_Deconexion.setMinimumSize(new java.awt.Dimension(213, 213));
        Button_Deconexion.setPreferredSize(new java.awt.Dimension(213, 213));
        Button_Deconexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeconexionActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Deconexion);
        Button_Deconexion.setBounds(180, 30, 60, 50);

        Button_Accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AccueilOff.png"))); // NOI18N
        Button_Accueil.setMaximumSize(new java.awt.Dimension(213, 213));
        Button_Accueil.setMinimumSize(new java.awt.Dimension(213, 213));
        Button_Accueil.setPreferredSize(new java.awt.Dimension(213, 213));
        Button_Accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AccueilActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Accueil);
        Button_Accueil.setBounds(250, 30, 60, 50);

        Btn_InformationPatient.setBackground(new java.awt.Color(255, 255, 255));
        Btn_InformationPatient.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Btn_InformationPatient.setForeground(new java.awt.Color(102, 102, 102));
        Btn_InformationPatient.setText("Information Patient");
        Btn_InformationPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InformationPatientActionPerformed(evt);
            }
        });

        Table_ListPatient.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Table_ListPatient.setForeground(new java.awt.Color(102, 102, 102));
        Table_ListPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jean ", "Bearnard", "AVC", "5"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Motif d'admission", "Numero de chambre"
            }
        ));
        Table_ListPatient.setShowVerticalLines(false);
        jScrollPane1.setViewportView(Table_ListPatient);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Rechercher");

        Text_RshPrenomPatient.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Text_RshPrenomPatient.setForeground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Prénom :");

        Text_RshNomPatient.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Text_RshNomPatient.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nom :");

        javax.swing.GroupLayout Panel_AccueilLayout = new javax.swing.GroupLayout(Panel_Accueil);
        Panel_Accueil.setLayout(Panel_AccueilLayout);
        Panel_AccueilLayout.setHorizontalGroup(
            Panel_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AccueilLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Panel_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_AccueilLayout.createSequentialGroup()
                        .addGroup(Panel_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_AccueilLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Text_RshNomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_RshPrenomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Btn_InformationPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_AccueilLayout.setVerticalGroup(
            Panel_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AccueilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text_RshNomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Text_RshPrenomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_InformationPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Panel_Accueil);
        Panel_Accueil.setBounds(350, 150, 870, 570);

        Label_bckgrd.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Label_bckgrd.setForeground(new java.awt.Color(102, 102, 102));
        Label_bckgrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background03.png"))); // NOI18N
        Label_bckgrd.setName("Label_bckgrd"); // NOI18N
        getContentPane().add(Label_bckgrd);
        Label_bckgrd.setBounds(0, -20, 1370, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
    
/******************************************************
                        RETOUR ACCUEIL                 
 /****************************************************/ 
    private void Button_AccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AccueilActionPerformed

    }//GEN-LAST:event_Button_AccueilActionPerformed


 /*****************************************************
                       DECONNEXION                     
 *****************************************************/  
    private void Button_DeconexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeconexionActionPerformed
        InterfaceConnexion connexion;
        try {
            connexion = new InterfaceConnexion();
            connexion.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ANESTHESISTE_Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Button_DeconexionActionPerformed

    private void Btn_InformationPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InformationPatientActionPerformed
        Panel_Accueil.setVisible(false);
     //   PanelInfoPatient.setVisible(true);
    }//GEN-LAST:event_Btn_InformationPatientActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_InformationPatient;
    private javax.swing.JButton Button_Accueil;
    private javax.swing.JButton Button_Deconexion;
    private javax.swing.JLabel Label_bckgrd;
    private javax.swing.JPanel Panel_Accueil;
    private javax.swing.JTable Table_ListPatient;
    private javax.swing.JTextField Text_RshNomPatient;
    private javax.swing.JTextField Text_RshPrenomPatient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
