/**************************************************************************************
                                                                                       
                 LA CLASSE SUIVANTE CORRESPOND A L'INTERFACE                           
                 D'IDENTIFICATION DES DIFFENRENTS UTILISATEUR                          
                                                                                       
 *************************************************************************************/
package Interface;


import fonctionalCore.DB_Link;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.sql.SQLException;
import javax.swing.Icon;
 
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author camille
 */
public class InterfaceConnexion extends javax.swing.JFrame {
    
/****************************************************************
                           CONSTRUCTEUR                          
 ***************************************************************/
    
    public InterfaceConnexion() throws SQLException {
        
        super("Connexion");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // Set the JFrame to maximize by default on opening
        setExtendedState(InterfaceConnexion.MAXIMIZED_BOTH); 

        initComponents();
        Dimension size = this.getSize(); // recupère size de la fentre
        Label_bckgrd.setSize(size); //ajuste la taille de l'image du background
        pack();
        this.setVisible(true);
        Label_MsgError.setVisible(false);
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Conexion = new javax.swing.JLabel();
        Label_Identifiant = new javax.swing.JLabel();
        Label_MotDePasse = new javax.swing.JLabel();
        TextField_Password = new javax.swing.JPasswordField();
        TextField_Identifiant = new javax.swing.JTextField();
        Btn_Connexion = new javax.swing.JButton();
        Label_MsgError = new javax.swing.JLabel();
        Label_bckgrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        Label_Conexion.setFont(new java.awt.Font("Arvo", 0, 48)); // NOI18N
        Label_Conexion.setForeground(new java.awt.Color(153, 153, 153));
        Label_Conexion.setText("Connexion");
        getContentPane().add(Label_Conexion);
        Label_Conexion.setBounds(610, 90, 360, 200);

        Label_Identifiant.setFont(new java.awt.Font("Arvo", 0, 24)); // NOI18N
        Label_Identifiant.setForeground(new java.awt.Color(153, 153, 153));
        Label_Identifiant.setText("Identifiant :");
        getContentPane().add(Label_Identifiant);
        Label_Identifiant.setBounds(450, 310, 170, 40);

        Label_MotDePasse.setFont(new java.awt.Font("Arvo", 0, 24)); // NOI18N
        Label_MotDePasse.setForeground(new java.awt.Color(153, 153, 153));
        Label_MotDePasse.setText("Mot de Passe :");
        getContentPane().add(Label_MotDePasse);
        Label_MotDePasse.setBounds(450, 370, 190, 40);

        TextField_Password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TextField_Password.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(TextField_Password);
        TextField_Password.setBounds(630, 370, 250, 40);

        TextField_Identifiant.setFont(new java.awt.Font("Arvo", 0, 24)); // NOI18N
        TextField_Identifiant.setForeground(new java.awt.Color(153, 153, 153));
        TextField_Identifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_IdentifiantActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Identifiant);
        TextField_Identifiant.setBounds(610, 310, 270, 40);

        Btn_Connexion.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Connexion.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Btn_Connexion.setForeground(new java.awt.Color(102, 102, 102));
        Btn_Connexion.setText("Connexion");
        Btn_Connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConnexionActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Connexion);
        Btn_Connexion.setBounds(750, 490, 130, 30);
        getContentPane().add(Label_MsgError);
        Label_MsgError.setBounds(450, 420, 430, 70);

        Label_bckgrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background03.png"))); // NOI18N
        Label_bckgrd.setName("Label_bckgrd"); // NOI18N
        getContentPane().add(Label_bckgrd);
        Label_bckgrd.setBounds(0, 0, 880, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_IdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_IdentifiantActionPerformed
 
    }//GEN-LAST:event_TextField_IdentifiantActionPerformed

    
    
    
    
/**********************************************************************************
                        IDENTIFICATION ET REDIRECTION              
 *********************************************************************************/
    private void Btn_ConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConnexionActionPerformed
       
        
        String identification = DB_Link.Identification(TextField_Identifiant.getText(),TextField_Password.getText());
        //le if sera du type if(identification=="secretaire"){...}else if(identification=="PH"){...}else{erreur}
        //autant de else if que de personnel différents
        if(identification=="secretaire"){  
           SA_Accueil sa_accueil = new SA_Accueil();
           sa_accueil.setVisible(true);
           this.dispose();    
       }else if(identification=="PH"){
           PH_Accueil ph_accueil = new PH_Accueil();
           ph_accueil.setVisible(true);
            this.dispose(); 
       }else if(identification =="UR") {
           URGENCE_Accueil ur_accueil = new URGENCE_Accueil();
            ur_accueil.setVisible(true);
            this.dispose(); 
       }else if(identification =="IN") {
           INFIRMIER_Accueil in_accueil = new INFIRMIER_Accueil(); 
            in_accueil.setVisible(true);
            this.dispose(); 
       }else if(identification =="AN") {
            ANESTHESISTE_Accueil an_accueil = new ANESTHESISTE_Accueil();
            an_accueil.setVisible(true);
            this.dispose(); 
       }
       else{ //si echec de connexion on renvoie un message d'erreur (definit dans DB_Link.connecterDB() ou DB_Link.Identification(string,string)
            URL resource = SA_Accueil.class.getResource("/Images/iconEror.png");
            Icon icon = new ImageIcon(resource);
            Label_MsgError.setIcon(icon);
            Label_MsgError.setText(identification);
            Label_MsgError.setVisible(true);
        }
        
      //PH_Accueil ph_accueil = new PH_Accueil();
      //ph_accueil.setVisible(true);
      
      
      
      
        
    }//GEN-LAST:event_Btn_ConnexionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Connexion;
    private javax.swing.JLabel Label_Conexion;
    private javax.swing.JLabel Label_Identifiant;
    private javax.swing.JLabel Label_MotDePasse;
    private javax.swing.JLabel Label_MsgError;
    private javax.swing.JLabel Label_bckgrd;
    private javax.swing.JTextField TextField_Identifiant;
    private javax.swing.JPasswordField TextField_Password;
    // End of variables declaration//GEN-END:variables
}
