/**************************************************************************************
                                                                                       
                      LA CLASSE SUIVANTE CORRESPOND A L'INTERFACES                     
                       DE SAISIE D'UN NOUVEAU PATIENT DES URGENCES                     
                                                                                       
 *************************************************************************************/
package Interface;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author camille
 */
public class URGENCE_NewPatient extends javax.swing.JFrame {

    
    
/****************************************************************
                            CONSTRUCTEUR                         
****************************************************************/
    public URGENCE_NewPatient() {
        initComponents();
        this.setTitle("Nouveau Patient");
        Date dateAndTime = Calendar.getInstance().getTime();
        JLabel dateTime = new JLabel(dateAndTime.toString());
        this.add(dateTime);
        ButtonGroup group = new ButtonGroup();
        group.add(inconnu);
        group.add(nouveau);
        inconnu.setSelected(true);
        textNom.setEditable(false);
        textPrenom.setEditable(false);
        textNom.setText("Doe");
        textPrenom.setText("John");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn_Enregistrer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inconnu = new javax.swing.JRadioButton();
        nouveau = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        textPrenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBox_MotifAdmission = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arvo", 0, 24)); // NOI18N
        jLabel1.setText("Nouveau Patient");

        Btn_Enregistrer.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Enregistrer.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Btn_Enregistrer.setText("Enregistrer");
        Btn_Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnregistrerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel2.setText("Information Patient :");

        inconnu.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        inconnu.setText("Inconnu");
        inconnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inconnuActionPerformed(evt);
            }
        });

        nouveau.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        nouveau.setText("Nouveau Patient");
        nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel3.setText("Nom :");

        jLabel4.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel4.setText("Prenom :");

        textNom.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        textNom.setText("jTextField1");

        textPrenom.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        textPrenom.setText("jTextField1");

        jLabel5.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel5.setText("Motif d'admission : ");

        comboBox_MotifAdmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Enregistrer))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(58, 58, 58)
                                        .addComponent(inconnu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nouveau)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(comboBox_MotifAdmission, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inconnu)
                    .addComponent(nouveau))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_MotifAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addComponent(Btn_Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
/*****************************************************
        RADIO BUTTON SI PATIENT = INCONNU                    
 *****************************************************/  
    private void inconnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inconnuActionPerformed
       textNom.setEditable(false);
       textPrenom.setEditable(false);
       textNom.setText("Doe");
       textPrenom.setText("John");
    }//GEN-LAST:event_inconnuActionPerformed

/*****************************************************
        RADIO BUTTON SI PATIENT = CONNU                    
 *****************************************************/  
    private void nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauActionPerformed
        textNom.setEditable(true);
        textPrenom.setEditable(true);

    }//GEN-LAST:event_nouveauActionPerformed

/*****************************************************
     ENREGISTRER LE PATIENT + ADMISSION AUTOMATIQUE   
*****************************************************/  
    private void Btn_EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnregistrerActionPerformed
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame, "Le patient est désormais hospitalisé en urgence.");
        this.dispose();
    }//GEN-LAST:event_Btn_EnregistrerActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Enregistrer;
    private javax.swing.JComboBox<String> comboBox_MotifAdmission;
    private javax.swing.JRadioButton inconnu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton nouveau;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textPrenom;
    // End of variables declaration//GEN-END:variables
}
