/**************************************************************************************
                                                                                       
                      LA CLASSE SUIVANTE CORRESPOND A L'INTERFACES                     
                       DE SAISIE D'UN NOUVEAU PATIENT DES URGENCES                     
                                                                                       
 *************************************************************************************/
package Interface;

import fonctionalCore.PH;
import fonctionalCore.Patient;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.log10;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author camille
 */
public class URGENCE_NewPatient extends javax.swing.JFrame {

    
    
/****************************************************************
                            CONSTRUCTEUR                         
****************************************************************/
    public URGENCE_NewPatient(PH leGarsConnecter) {
        initComponents();
        this.setTitle("Nouveau Patient");
        Date dateAndTime = Calendar.getInstance().getTime();
        JLabel dateTime = new JLabel(dateAndTime.toString());
        this.add(dateTime);
        ButtonGroup group = new ButtonGroup();
        group.add(inconnu);
        group.add(nouveau);
        inconnu.setSelected(true);
        Text_Nom.setEditable(false);
        Text_Prenom.setEditable(false);
        Text_Nom.setText("Doe");
        Text_Prenom.setText("John");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        
        quiSuisJe =new PH(((PH)leGarsConnecter).getId_PH(),((PH)leGarsConnecter).getSpecialite(),((PH)leGarsConnecter).getNom(),((PH)leGarsConnecter).getPrenom(),((PH)leGarsConnecter).getnTel());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn_Enregistrer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inconnu = new javax.swing.JRadioButton();
        nouveau = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Text_Nom = new javax.swing.JTextField();
        Text_Prenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Text_Motif = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arvo", 0, 24)); // NOI18N
        jLabel1.setText("Nouveau Patient");

        Btn_Enregistrer.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Enregistrer.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Btn_Enregistrer.setText("Enregistrer");
        Btn_Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnregistrerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel2.setText("Information Patient :");

        inconnu.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        inconnu.setText("Inconnu");
        inconnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inconnuActionPerformed(evt);
            }
        });

        nouveau.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        nouveau.setText("Nouveau Patient");
        nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel3.setText("Nom :");

        jLabel4.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel4.setText("Prenom :");

        Text_Nom.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N

        Text_Prenom.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        Text_Prenom.setText("jTextField1");

        jLabel5.setFont(new java.awt.Font("Arvo", 0, 14)); // NOI18N
        jLabel5.setText("Motif d'admission : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Enregistrer))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(58, 58, 58)
                                        .addComponent(inconnu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Text_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nouveau)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Text_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Text_Motif)))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inconnu)
                    .addComponent(nouveau))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Text_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_Motif, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addComponent(Btn_Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
/*****************************************************
        RADIO BUTTON SI PATIENT = INCONNU                    
 *****************************************************/  
    private void inconnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inconnuActionPerformed
       Text_Nom.setEditable(false);
       Text_Prenom.setEditable(false);
       Text_Nom.setText("Doe");
       Text_Prenom.setText("John");
    }//GEN-LAST:event_inconnuActionPerformed

/*****************************************************
        RADIO BUTTON SI PATIENT = CONNU                    
 *****************************************************/  
    private void nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauActionPerformed
        Text_Nom.setEditable(true);
        Text_Prenom.setEditable(true);

    }//GEN-LAST:event_nouveauActionPerformed

/*****************************************************
     ENREGISTRER LE PATIENT + ADMISSION AUTOMATIQUE   
*****************************************************/  
    private void Btn_EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnregistrerActionPerformed
        if ((!Text_Nom.getText().equals("")) && (!Text_Prenom.getText().equals(""))) { 
            if ((Pattern.matches("^[\\p{L} .'-]+$", Text_Nom.getText())) && (Pattern.matches("^[\\p{L} .'-]+$", Text_Prenom.getText()))) {
 
                    Date dateAndTime = Calendar.getInstance().getTime();
                    int annee = 1900+dateAndTime.getYear();
                    int digit = annee % 100;

                    String lipp = Integer.toString(digit);
                    int nbDePatientCetteAnnee = Patient.CountLeNombreDePatientCetteAnnee(digit);
                    int numDePatient = nbDePatientCetteAnnee + 1;
                    int log = (int) (log10((numDePatient)) + 1);
                    int nbDeChiffreAAjouter = 7 - log;
                    for (int i = 0; i < nbDeChiffreAAjouter; i++) {
                        lipp = lipp + "0";
                    }

                    lipp = lipp + (numDePatient + 1);
                    int IPP = Integer.parseInt(lipp);

                    String message = Patient.AjouterPatient(IPP, Text_Prenom.getText(), Text_Nom.getText(), "","","", "", "", "","", "", "",0);
                    
                    if(Text_Motif.equals("")){
                        JFrame frame = new JFrame();
                       JOptionPane.showMessageDialog(frame, "Veuillez saisir un motif d'admission");
                    }else{
                        String motifAdmission = Text_Motif.getText();

                        int mois = dateAndTime.getMonth()+1;
                        String date =annee+"-"+mois+"-"+dateAndTime.getDate()+" "+dateAndTime.getHours()+":"+dateAndTime.getMinutes()+":"+dateAndTime.getSeconds();
                        
                        int hospi_consult=1;
                       

                        message = Patient.NouvelleAdmission(lipp,hospi_consult,date,quiSuisJe.getId_PH(),motifAdmission,"urgence");
                    }
                    JFrame frame = new JFrame();
                    JOptionPane.showMessageDialog(frame, "Le patient à été ajouter et admis en hospitalisation au urgence");
                    

            } else {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "Le nom et/ou le prenom du patient contient des caractères invalides");
            }
        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, " Le nom et/ou le prenom du patient est manquant.");
        }

        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame, "Le patient est désormais hospitalisé en urgence.");
        this.dispose();
    }//GEN-LAST:event_Btn_EnregistrerActionPerformed

    /**
     * @param args the command line arguments
     */

PH quiSuisJe;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Enregistrer;
    private javax.swing.JTextField Text_Motif;
    private javax.swing.JTextField Text_Nom;
    private javax.swing.JTextField Text_Prenom;
    private javax.swing.JRadioButton inconnu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton nouveau;
    // End of variables declaration//GEN-END:variables
}
